# backend/app/models.py
"""
SQLAlchemy ORM models for Phantasm-DB.

Tables:
  - users         Core identity and role store.
  - audit_logs    Forensic log of every request (real + honeypot).
  - otp_requests  Time-limited one-time passwords for MFA.
"""

import enum
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean, Column, DateTime, Enum, ForeignKey,
    Integer, String, Text, func
)
from sqlalchemy.orm import relationship

from .database import Base


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class UserRole(str, enum.Enum):
    admin   = "admin"
    doctor  = "doctor"
    patient = "patient"


# ---------------------------------------------------------------------------
# Users
# ---------------------------------------------------------------------------

class User(Base):
    """
    Represents every authenticated principal in the system.

    is_flagged_as_attacker  — Set by security.py when suspicious behaviour
                              is detected.  Triggers honeypot routing.
    failed_login_count      — Incremented on each bad credential attempt.
    """
    __tablename__ = "users"

    id                    = Column(Integer, primary_key=True, index=True)
    email                 = Column(String(255), unique=True, nullable=False, index=True)
    password_hash         = Column(String(255), nullable=False)
    role                  = Column(Enum(UserRole), nullable=False, default=UserRole.patient)
    full_name             = Column(String(255), nullable=True)
    mrn                   = Column(String(50),  unique=True, nullable=True, index=True)   # Medical Record Number (patients)
    npi                   = Column(String(50),  unique=True, nullable=True, index=True)   # National Provider ID (doctors)
    is_active             = Column(Boolean, default=True, nullable=False)
    is_flagged_as_attacker= Column(Boolean, default=False, nullable=False, index=True)
    failed_login_count    = Column(Integer, default=0, nullable=False)
    last_login_ip         = Column(String(64), nullable=True)
    created_at            = Column(DateTime(timezone=True), server_default=func.now())
    updated_at            = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    audit_logs   = relationship("AuditLog",   back_populates="user",    lazy="select")
    otp_requests = relationship("OTPRequest", back_populates="user",    lazy="select")

    def __repr__(self) -> str:
        return f"<User id={self.id} email={self.email!r} role={self.role}>"


# ---------------------------------------------------------------------------
# Audit Logs
# ---------------------------------------------------------------------------

class AuditLog(Base):
    """
    Immutable forensic record of every interaction with the system.

    is_honeypot_action  — True when this log entry was generated by a
                          trapped attacker interacting with a honeypot page.
    is_malicious        — True when security middleware detected an attack
                          signature in the request.
    """
    __tablename__ = "audit_logs"

    id                 = Column(Integer, primary_key=True, index=True)
    timestamp          = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    ip_address         = Column(String(64), nullable=False, index=True)
    user_agent         = Column(String(512), nullable=True)
    user_id            = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    action             = Column(String(128), nullable=False)         # e.g. "LOGIN_ATTEMPT", "VIEW_PATIENT", "SUBMIT_NOTES"
    endpoint           = Column(String(512), nullable=False)
    http_method        = Column(String(10), nullable=False, default="GET")
    payload            = Column(Text, nullable=True)                  # JSON-encoded request body (redacted if needed)
    response_status    = Column(Integer, nullable=True)
    is_malicious       = Column(Boolean, default=False, nullable=False, index=True)
    is_honeypot_action = Column(Boolean, default=False, nullable=False, index=True)
    detection_reason   = Column(String(512), nullable=True)           # Human-readable reason for flagging

    # Relationships
    user = relationship("User", back_populates="audit_logs")

    def __repr__(self) -> str:
        return (
            f"<AuditLog id={self.id} action={self.action!r} "
            f"ip={self.ip_address!r} malicious={self.is_malicious}>"
        )


# ---------------------------------------------------------------------------
# OTP Requests
# ---------------------------------------------------------------------------

class OTPRequest(Base):
    """
    Time-limited one-time password record.

    A new record is created each time /auth/request-otp is called.
    The record is soft-deleted (is_used=True) after successful verification
    to prevent replay attacks.
    """
    __tablename__ = "otp_requests"

    id         = Column(Integer, primary_key=True, index=True)
    user_id    = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    otp_code   = Column(String(6), nullable=False)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    is_used    = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    created_ip = Column(String(64), nullable=True)

    # Relationships
    user = relationship("User", back_populates="otp_requests")

    def is_valid(self) -> bool:
        """Returns True if the OTP has not been used and has not expired."""
        return (not self.is_used) and (datetime.now(timezone.utc) < self.expires_at)

    def __repr__(self) -> str:
        return f"<OTPRequest id={self.id} user_id={self.user_id} used={self.is_used}>"
